# Generated by Django 3.2.7 on 2021-09-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consultaClinica',
            new_name='novoPaciente',
        ),
    ]
